[build]
  publish = "."
  command = "echo 'Skipping build step'"

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=3600"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
